#!/bin/bash
set -ev

unset EXEC
EXEC="mpirun -np 4 ddSim"

unset LOGFILE
MODE=nvt
if [ $# -gt 0 ]; then
   LOGFILE=$1
   if [ $# -gt 1 ]; then
      MODE=$2
   fi
fi
PARAM=param.$MODE
COMMAND=command

# Make or clean directory out
if [ ! -d "out" ]; then
   mkdir out
else
   rm -f out/*
fi

# Run simulation
if [ -z "$LOGFILE" ]; then
   $EXEC -q -e -p $PARAM -c $COMMAND
else
   $EXEC -q -e -p $PARAM -c $COMMAND > out/$LOGFILE
fi

# Make or clean directory rst, if necessary
if [ ! -d "rst" ]; then
   mkdir rst
else
   rm -f rst/*
fi

# Restart simulation, write outputs to rst/
if [ -z "$LOGFILE" ]; then
   $EXEC -q -e -r restart -c commrst -o rst/ 
else
   $EXEC -q -e -r restart -c commrst -o rst/  > rst/$LOGFILE
fi


