#!/bin/bash
set -ev

MODE=nve
if [ $# -gt 0 ]; then
   MODE=$1
fi
PARAM=param.$MODE
COMMANDS=commands
COMMRST=commrst

# Make or clean directory out
if [ ! -d "out" ]; then
   mkdir out
else
   rm -f out/*
fi

# Run simulation, write output to out/
mdSim -e -p $PARAM -c $COMMANDS

# Make or clean directory rst, if necessary
if [ ! -d "rst" ]; then
   mkdir rst
else
   rm -f rst/*
fi

# Restart simulation, write outputs to rst/
mdSim -q -e -r restart -c $COMMRST -o rst/

