#!/bin/bash
set -ev

unset EXEC
EXEC="mpirun -np 8 ddSim"

unset LOGFILE
MODE=nvt
if [ $# -gt 0 ]; then
   MODE=$1
   if [ $# -gt 1 ]; then
      LOGFILE=$2 
   fi
fi
PARAM=param.$MODE

# Make or clean directory out
if [ ! -d "out" ]; then
   mkdir out
else
   rm -f out/*
fi

# Run simulation
if [ -z "$LOGFILE" ]; then
   $EXEC -q -e -p $PARAM -c command
else
   $EXEC -q -e -p $PARAM -c command > $LOGFILE
   mv $LOGFILE out
fi

# Make or clean directory rst, if necessary
if [ ! -d "rst" ]; then
   mkdir rst
else
   rm -f rst/*
fi

# Restart simulation, write outputs to rst/
if [ -z "$LOGFILE" ]; then
   $EXEC -q -e -r restart -c commrst -o rst/ 
else
   $EXEC -q -e -r restart -c commrst -o rst/  > $LOGFILE
   mv $LOGFILE rst
fi


