#!/bin/bash
set -ev

MODE=atom
if [ $# -gt 0 ]; then
   MODE=$1
fi
PARAM=param.$MODE
COMMAND=command.$MODE
COMMRST=commrst.$MODE
echo "Parameter file : " $PARAM
echo "Command file   : " $COMMAND

# Make or clean directory out
if [ ! -d "out" ]; then
   mkdir out
else
   rm -f out/*
fi

# Run simulation, write output to out/
mcSim -e -p $PARAM -c $COMMAND

# Make or clean directory rst, if necessary
if [ ! -d "rst" ]; then
   mkdir rst
else
   rm -f rst/*
fi

# Restart simulation, write outputs to rst/
mcSim -q -e -r restart -c $COMMRST -o rst/

